package com.stc.pattysmorestuff.init;

import java.util.*;
import net.minecraft.fluid.*;
import com.stc.pattysmorestuff.items.infbuckets.*;
import com.stc.pattysmorestuff.items.wand.*;
import com.stc.pattysmorestuff.handlers.*;
import net.minecraft.inventory.*;
import com.stc.pattysmorestuff.items.toolsandarmors.*;
import net.minecraft.item.*;
import com.stc.pattysmorestuff.items.foods.*;
import com.stc.pattysmorestuff.items.drinks.*;
import com.stc.pattysmorestuff.items.*;

public class ModItems
{
    public static final List<Item> ITEMS;
    public static Item obsidian_ingot;
    public static Item obsidian_chunk;
    public static Item inf_water_bucket;
    public static Item inf_lava_bucket;
    public static Item time_wand;
    public static Item light_wand;
    public static Item weather_wand;
    public static Item knife;
    public static Item wrench;
    public static Item iron_dust;
    public static Item gold_dust;
    public static Item obsidian_dust;
    public static Item diamond_dust;
    public static Item emerald_dust;
    public static Item coal_dust;
    public static Item nstar_pickaxe;
    public static Item nstar_axe;
    public static Item nstar_shovel;
    public static Item nstar_hoe;
    public static Item nstar_sword;
    public static Item nstar_paxel;
    public static Item netherstar_battle_axe;
    public static Item nstar_bow;
    public static Item nstar_scythe;
    public static Item nstar_hammer;
    public static Item nstar_lumber_axe;
    public static Item nstar_excavator;
    public static Item nether_star_helmet;
    public static Item nether_star_chestplate;
    public static Item nether_star_leggings;
    public static Item nether_star_boots;
    public static Item emerald_pickaxe;
    public static Item emerald_axe;
    public static Item emerald_shovel;
    public static Item emerald_sword;
    public static Item emerald_hoe;
    public static Item emerald_paxel;
    public static Item emerald_battle_axe;
    public static Item emerald_bow;
    public static Item emerald_scythe;
    public static Item emerald_hammer;
    public static Item emerald_lumber_axe;
    public static Item emerald_excavator;
    public static Item emerald_helmet;
    public static Item emerald_chestplate;
    public static Item emerald_leggings;
    public static Item emerald_boots;
    public static Item obsidian_pickaxe;
    public static Item obsidian_axe;
    public static Item obsidian_shovel;
    public static Item obsidian_sword;
    public static Item obsidian_hoe;
    public static Item obsidian_paxel;
    public static Item obsidian_battle_axe;
    public static Item obsidian_bow;
    public static Item obsidian_scythe;
    public static Item obsidian_hammer;
    public static Item obsidian_lumber_axe;
    public static Item obsidian_excavator;
    public static Item obsidian_helmet;
    public static Item obsidian_chestplate;
    public static Item obsidian_leggings;
    public static Item obsidian_boots;
    public static Item ender_pickaxe;
    public static Item ender_axe;
    public static Item ender_shovel;
    public static Item ender_hoe;
    public static Item ender_sword;
    public static Item ender_paxel;
    public static Item ender_battle_axe;
    public static Item ender_bow;
    public static Item ender_scythe;
    public static Item ender_hammer;
    public static Item ender_lumber_axe;
    public static Item ender_excavator;
    public static Item ender_helmet;
    public static Item ender_chestplate;
    public static Item ender_leggings;
    public static Item ender_boots;
    public static Item coal_pickaxe;
    public static Item coal_axe;
    public static Item coal_shovel;
    public static Item coal_hoe;
    public static Item coal_sword;
    public static Item coal_paxel;
    public static Item coal_battle_axe;
    public static Item coal_bow;
    public static Item coal_scythe;
    public static Item coal_hammer;
    public static Item coal_lumber_axe;
    public static Item coal_excavator;
    public static Item coal_helmet;
    public static Item coal_chestplate;
    public static Item coal_leggings;
    public static Item coal_boots;
    public static Item quartz_pickaxe;
    public static Item quartz_axe;
    public static Item quartz_shovel;
    public static Item quartz_sword;
    public static Item quartz_hoe;
    public static Item quartz_paxel;
    public static Item quartz_battle_axe;
    public static Item quartz_bow;
    public static Item quartz_scythe;
    public static Item quartz_hammer;
    public static Item quartz_lumber_axe;
    public static Item quartz_excavator;
    public static Item quartz_helmet;
    public static Item quartz_chestplate;
    public static Item quartz_leggings;
    public static Item quartz_boots;
    public static Item glowstone_pickaxe;
    public static Item glowstone_axe;
    public static Item glowstone_shovel;
    public static Item glowstone_sword;
    public static Item glowstone_hoe;
    public static Item glowstone_paxel;
    public static Item glowstone_battle_axe;
    public static Item glowstone_bow;
    public static Item glowstone_scythe;
    public static Item glowstone_hammer;
    public static Item glowstone_lumber_axe;
    public static Item glowstone_excavator;
    public static Item glowstone_helmet;
    public static Item glowstone_chestplate;
    public static Item glowstone_leggings;
    public static Item glowstone_boots;
    public static Item brick_pickaxe;
    public static Item brick_axe;
    public static Item brick_shovel;
    public static Item brick_hoe;
    public static Item brick_sword;
    public static Item brick_paxel;
    public static Item brick_battle_axe;
    public static Item brick_bow;
    public static Item brick_scythe;
    public static Item brick_hammer;
    public static Item brick_lumber_axe;
    public static Item brick_excavator;
    public static Item brick_helmet;
    public static Item brick_chestplate;
    public static Item brick_leggings;
    public static Item brick_boots;
    public static Item nbrick_pickaxe;
    public static Item nbrick_axe;
    public static Item nbrick_shovel;
    public static Item nbrick_hoe;
    public static Item nbrick_sword;
    public static Item nbrick_paxel;
    public static Item netherbrick_battle_axe;
    public static Item netherbrick_bow;
    public static Item nbrick_scythe;
    public static Item nbrick_hammer;
    public static Item nbrick_lumber_axe;
    public static Item nbrick_excavator;
    public static Item nether_brick_helmet;
    public static Item nether_brick_chestplate;
    public static Item nether_brick_leggings;
    public static Item nether_brick_boots;
    public static Item redstone_pickaxe;
    public static Item redstone_axe;
    public static Item redstone_shovel;
    public static Item redstone_hoe;
    public static Item redstone_sword;
    public static Item redstone_paxel;
    public static Item redstone_battle_axe;
    public static Item redstone_bow;
    public static Item redstone_scythe;
    public static Item redstone_hammer;
    public static Item redstone_lumber_axe;
    public static Item redstone_excavator;
    public static Item redstone_helmet;
    public static Item redstone_chestplate;
    public static Item redstone_leggings;
    public static Item redstone_boots;
    public static Item blaze_pickaxe;
    public static Item blaze_axe;
    public static Item blaze_shovel;
    public static Item blaze_hoe;
    public static Item blaze_sword;
    public static Item blaze_paxel;
    public static Item blaze_battle_axe;
    public static Item blaze_bow;
    public static Item blaze_scythe;
    public static Item blaze_hammer;
    public static Item blaze_lumber_axe;
    public static Item blaze_excavator;
    public static Item blaze_helmet;
    public static Item blaze_chestplate;
    public static Item blaze_leggings;
    public static Item blaze_boots;
    public static Item magma_cream_pickaxe;
    public static Item magma_cream_axe;
    public static Item magma_cream_shovel;
    public static Item magma_cream_hoe;
    public static Item magma_cream_sword;
    public static Item magma_cream_paxel;
    public static Item magmacream_battle_axe;
    public static Item magma_cream_bow;
    public static Item magma_cream_scythe;
    public static Item magma_cream_hammer;
    public static Item magma_cream_lumber_axe;
    public static Item magma_cream_excavator;
    public static Item magma_cream_helmet;
    public static Item magma_cream_chestplate;
    public static Item magma_cream_leggings;
    public static Item magma_cream_boots;
    public static Item sandstone_pickaxe;
    public static Item sandstone_axe;
    public static Item sandstone_shovel;
    public static Item sandstone_hoe;
    public static Item sandstone_sword;
    public static Item sandstone_paxel;
    public static Item sandstone_battle_axe;
    public static Item sandstone_bow;
    public static Item sandstone_scythe;
    public static Item sandstone_hammer;
    public static Item sandstone_lumber_axe;
    public static Item sandstone_helmet;
    public static Item sandstone_chestplate;
    public static Item sandstone_leggings;
    public static Item sandstone_boots;
    public static Item soul_sand_pickaxe;
    public static Item soul_sand_axe;
    public static Item soul_sand_shovel;
    public static Item soul_sand_hoe;
    public static Item soul_sand_sword;
    public static Item soul_sand_paxel;
    public static Item soulsand_battle_axe;
    public static Item soul_sand_bow;
    public static Item soul_sand_scythe;
    public static Item soul_sand_hammer;
    public static Item soul_sand_lumber_axe;
    public static Item soul_sand_helmet;
    public static Item soul_sand_chestplate;
    public static Item soul_sand_leggings;
    public static Item soul_sand_boots;
    public static Item netherbrickred_pickaxe;
    public static Item netherbrickred_axe;
    public static Item netherbrickred_shovel;
    public static Item netherbrickred_hoe;
    public static Item netherbrickred_sword;
    public static Item netherbrickred_paxel;
    public static Item netherbrickred_battle_axe;
    public static Item netherbrickred_bow;
    public static Item netherbrickred_scythe;
    public static Item netherbrickred_hammer;
    public static Item netherbrickred_lumber_axe;
    public static Item red_netherbrick_helmet;
    public static Item red_netherbrick_chestplate;
    public static Item red_netherbrick_leggings;
    public static Item red_netherbrick_boots;
    public static Item wooden_paxel;
    public static Item wooden_battle_axe;
    public static Item wood_scythe;
    public static Item wooden_hammer;
    public static Item wooden_lumber_axe;
    public static Item stone_paxel;
    public static Item stone_battle_axe;
    public static Item stone_bow;
    public static Item stone_scythe;
    public static Item stone_hammer;
    public static Item stone_lumber_axe;
    public static Item iron_paxel;
    public static Item iron_battle_axe;
    public static Item iron_bow;
    public static Item iron_scythe;
    public static Item iron_hammer;
    public static Item iron_lumber_axe;
    public static Item iron_excavator;
    public static Item gold_paxel;
    public static Item gold_battle_axe;
    public static Item gold_bow;
    public static Item gold_scythe;
    public static Item gold_hammer;
    public static Item gold_lumber_axe;
    public static Item gold_excavator;
    public static Item diamond_paxel;
    public static Item diamond_battle_axe;
    public static Item diamond_bow;
    public static Item diamond_scythe;
    public static Item diamond_hammer;
    public static Item diamond_lumber_axe;
    public static Item diamond_excavator;
    public static Item fried_egg;
    public static Item bacon_raw;
    public static Item bacon_cooked;
    public static Item sausage_raw;
    public static Item sausage_cooked;
    public static Item baguette_roll;
    public static Item baguette_bacon;
    public static Item baguette_egg;
    public static Item baguette_eggbacon;
    public static Item baguette_sausage;
    public static Item baguette_baconsausage;
    public static Item baguette_eggsausage;
    public static Item baguette_eggbaconsausage;
    public static Item apple_pie;
    public static Item toast;
    public static Item flour;
    public static Item fruit_salad;
    public static Item double_choc_cookie;
    public static Item apple_juice;
    public static Item melon_juice;
    public static Item carrot_juice;
    public static Item beetroot_juice;
    public static Item pumpkin_juice;
    public static Item bottle_milk;
    public static Item bottle_chocolate_milk;
    public static Item apple_slushie;
    public static Item melon_slushie;
    public static Item carrot_slushie;
    public static Item beetroot_slushie;
    public static Item pumpkin_slushie;
    public static Item apple_smoothie;
    public static Item melon_smoothie;
    public static Item carrot_smoothie;
    public static Item beetroot_smoothie;
    public static Item pumpkin_smoothie;
    public static Item miners_helmet;
    public static Item magnet;
    public static Item ring_of_flight;
    public static Item sweet_berrie_pie;

    static {
        ITEMS = new ArrayList<Item>();
        ModItems.obsidian_ingot = new ItemObsidianIngot("obsidian_ingot", new Item.Properties().group(ModTabs.tabPattysMisc));
        ModItems.obsidian_chunk = new ItemBase("obsidian_chunk", new Item.Properties().group(ModTabs.tabPattysMisc));
        ModItems.inf_water_bucket = new ItemInfWaterBucket("inf_water_bucket", (Fluid)Fluids.WATER, new Item.Properties().group(ModTabs.tabPattysMisc));
        ModItems.inf_lava_bucket = new ItemInfLavaBucket("inf_lava_bucket", (Fluid)Fluids.LAVA, new Item.Properties().group(ModTabs.tabPattysMisc));
        ModItems.time_wand = new ItemTimeWand("time_wand", new Item.Properties().group(ModTabs.tabPattysMisc));
        ModItems.light_wand = new ItemLightWand("light_wand", new Item.Properties().group(ModTabs.tabPattysMisc));
        ModItems.weather_wand = new ItemWeatherWand("weather_wand", new Item.Properties().group(ModTabs.tabPattysMisc));
        ModItems.knife = new ItemKnife("knife", new Item.Properties().group(ModTabs.tabPattysMisc));
        ModItems.wrench = new ItemWrench("wrench", new Item.Properties().group(ModTabs.tabPattysMisc));
        ModItems.iron_dust = new ItemBase("iron_dust", new Item.Properties().group(ModTabs.tabPattysMisc));
        ModItems.gold_dust = new ItemBase("gold_dust", new Item.Properties().group(ModTabs.tabPattysMisc));
        ModItems.obsidian_dust = new ItemBase("obsidian_dust", new Item.Properties().group(ModTabs.tabPattysMisc));
        ModItems.diamond_dust = new ItemBase("diamond_dust", new Item.Properties().group(ModTabs.tabPattysMisc));
        ModItems.emerald_dust = new ItemBase("emerald_dust", new Item.Properties().group(ModTabs.tabPattysMisc));
        ModItems.coal_dust = new ItemBase("coal_dust", new Item.Properties().group(ModTabs.tabPattysMisc));
        ModItems.nstar_pickaxe = (Item)new ItemCustomPickaxe("nstar_pickaxe", (IItemTier)PattysToolMaterial.NSTAR, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.nstar_axe = (Item)new ItemCustomAxe("nstar_axe", (IItemTier)PattysToolMaterial.NSTAR, 5.0f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.nstar_shovel = (Item)new ItemCustomSpade("nstar_shovel", (IItemTier)PattysToolMaterial.NSTAR, 1.5f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.nstar_hoe = (Item)new ItemCustomHoe("nstar_hoe", (IItemTier)PattysToolMaterial.NSTAR, 0.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.nstar_sword = (Item)new ItemCustomSword("nstar_sword", (IItemTier)PattysToolMaterial.NSTAR, 3, -2.4f, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.nstar_paxel = (Item)new ItemPaxel("nstar_paxel", (IItemTier)PattysToolMaterial.NSTAR_PAXEL, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.netherstar_battle_axe = (Item)new ItemBattleaxe("netherstar_battle_axe", (IItemTier)PattysToolMaterial.NSTAR, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.nstar_bow = (Item)new ItemCustomBow("nstar_bow", new Item.Properties().group(ModTabs.tabPattysCombat).defaultMaxDamage(PattysToolMaterial.NSTAR.getMaxUses()));
        ModItems.nstar_scythe = new ItemCustomScythe("nstar_scythe", (IItemTier)PattysToolMaterial.NSTAR, 0.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.nstar_hammer = (Item)new ItemCustomHammer("nstar_hammer", (IItemTier)PattysToolMaterial.NSTAR, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.nstar_lumber_axe = (Item)new ItemLumberAxe("nstar_lumber_axe", (IItemTier)PattysToolMaterial.NSTAR, 5.0f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.nstar_excavator = (Item)new ItemExcavator("nstar_excavator", (IItemTier)PattysToolMaterial.NSTAR, 1, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.nether_star_helmet = (Item)new ItemMoreArmor("nether_star_helmet", (IArmorMaterial)PattysArmorMaterial.NSTAR, "nether_star", EquipmentSlotType.HEAD, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.nether_star_chestplate = (Item)new ItemMoreArmor("nether_star_chestplate", (IArmorMaterial)PattysArmorMaterial.NSTAR, "nether_star", EquipmentSlotType.CHEST, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.nether_star_leggings = (Item)new ItemMoreArmor("nether_star_leggings", (IArmorMaterial)PattysArmorMaterial.NSTAR, "nether_star", EquipmentSlotType.LEGS, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.nether_star_boots = (Item)new ItemMoreArmor("nether_star_boots", (IArmorMaterial)PattysArmorMaterial.NSTAR, "nether_star", EquipmentSlotType.FEET, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.emerald_pickaxe = (Item)new ItemCustomPickaxe("emerald_pickaxe", (IItemTier)PattysToolMaterial.EMERALD, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.emerald_axe = (Item)new ItemCustomAxe("emerald_axe", (IItemTier)PattysToolMaterial.EMERALD, 5.0f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.emerald_shovel = (Item)new ItemCustomSpade("emerald_shovel", (IItemTier)PattysToolMaterial.EMERALD, 1.5f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.emerald_sword = (Item)new ItemCustomSword("emerald_sword", (IItemTier)PattysToolMaterial.EMERALD, 3, -2.4f, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.emerald_hoe = (Item)new ItemCustomHoe("emerald_hoe", (IItemTier)PattysToolMaterial.EMERALD, 0.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.emerald_paxel = (Item)new ItemPaxel("emerald_paxel", (IItemTier)PattysToolMaterial.EMERALD_PAXEL, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.emerald_battle_axe = (Item)new ItemBattleaxe("emerald_battle_axe", (IItemTier)PattysToolMaterial.EMERALD, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.emerald_bow = (Item)new ItemCustomBow("emerald_bow", new Item.Properties().group(ModTabs.tabPattysCombat).defaultMaxDamage(PattysToolMaterial.EMERALD.getMaxUses()));
        ModItems.emerald_scythe = new ItemCustomScythe("emerald_scythe", (IItemTier)PattysToolMaterial.EMERALD, 0.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.emerald_hammer = (Item)new ItemCustomHammer("emerald_hammer", (IItemTier)PattysToolMaterial.EMERALD, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.emerald_lumber_axe = (Item)new ItemLumberAxe("emerald_lumber_axe", (IItemTier)PattysToolMaterial.EMERALD, 5.0f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.emerald_excavator = (Item)new ItemExcavator("emerald_excavator", (IItemTier)PattysToolMaterial.EMERALD, 1, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.emerald_helmet = (Item)new ItemMoreArmor("emerald_helmet", (IArmorMaterial)PattysArmorMaterial.EMERALD, "emerald", EquipmentSlotType.HEAD, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.emerald_chestplate = (Item)new ItemMoreArmor("emerald_chestplate", (IArmorMaterial)PattysArmorMaterial.EMERALD, "emerald", EquipmentSlotType.CHEST, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.emerald_leggings = (Item)new ItemMoreArmor("emerald_leggings", (IArmorMaterial)PattysArmorMaterial.EMERALD, "emerald", EquipmentSlotType.LEGS, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.emerald_boots = (Item)new ItemMoreArmor("emerald_boots", (IArmorMaterial)PattysArmorMaterial.EMERALD, "emerald", EquipmentSlotType.FEET, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.obsidian_pickaxe = (Item)new ItemCustomPickaxe("obsidian_pickaxe", (IItemTier)PattysToolMaterial.OBSIDIAN, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.obsidian_axe = (Item)new ItemCustomAxe("obsidian_axe", (IItemTier)PattysToolMaterial.OBSIDIAN, 5.0f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.obsidian_shovel = (Item)new ItemCustomSpade("obsidian_shovel", (IItemTier)PattysToolMaterial.OBSIDIAN, 1.5f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.obsidian_sword = (Item)new ItemCustomSword("obsidian_sword", (IItemTier)PattysToolMaterial.OBSIDIAN, 3, -2.4f, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.obsidian_hoe = (Item)new ItemCustomHoe("obsidian_hoe", (IItemTier)PattysToolMaterial.OBSIDIAN, 0.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.obsidian_paxel = (Item)new ItemPaxel("obsidian_paxel", (IItemTier)PattysToolMaterial.OBSIDIAN_PAXEL, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.obsidian_battle_axe = (Item)new ItemBattleaxe("obsidian_battle_axe", (IItemTier)PattysToolMaterial.OBSIDIAN, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.obsidian_bow = (Item)new ItemCustomBow("obsidian_bow", new Item.Properties().group(ModTabs.tabPattysCombat).defaultMaxDamage(PattysToolMaterial.OBSIDIAN.getMaxUses()));
        ModItems.obsidian_scythe = new ItemCustomScythe("obsidian_scythe", (IItemTier)PattysToolMaterial.OBSIDIAN, 0.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.obsidian_hammer = (Item)new ItemCustomHammer("obsidian_hammer", (IItemTier)PattysToolMaterial.OBSIDIAN, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.obsidian_lumber_axe = (Item)new ItemLumberAxe("obsidian_lumber_axe", (IItemTier)PattysToolMaterial.OBSIDIAN, 5.0f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.obsidian_excavator = (Item)new ItemExcavator("obsidian_excavator", (IItemTier)PattysToolMaterial.OBSIDIAN, 1, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.obsidian_helmet = (Item)new ItemMoreArmor("obsidian_helmet", (IArmorMaterial)PattysArmorMaterial.OBSIDIAN, "obsidian", EquipmentSlotType.HEAD, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.obsidian_chestplate = (Item)new ItemMoreArmor("obsidian_chestplate", (IArmorMaterial)PattysArmorMaterial.OBSIDIAN, "obsidian", EquipmentSlotType.CHEST, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.obsidian_leggings = (Item)new ItemMoreArmor("obsidian_leggings", (IArmorMaterial)PattysArmorMaterial.OBSIDIAN, "obsidian", EquipmentSlotType.LEGS, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.obsidian_boots = (Item)new ItemMoreArmor("obsidian_boots", (IArmorMaterial)PattysArmorMaterial.OBSIDIAN, "obsidian", EquipmentSlotType.FEET, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.ender_pickaxe = (Item)new ItemCustomPickaxe("ender_pickaxe", (IItemTier)PattysToolMaterial.ENDER, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.ender_axe = (Item)new ItemCustomAxe("ender_axe", (IItemTier)PattysToolMaterial.ENDER, 5.0f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.ender_shovel = (Item)new ItemCustomSpade("ender_shovel", (IItemTier)PattysToolMaterial.ENDER, 1.5f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.ender_hoe = (Item)new ItemCustomHoe("ender_hoe", (IItemTier)PattysToolMaterial.ENDER, 0.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.ender_sword = (Item)new ItemCustomSword("ender_sword", (IItemTier)PattysToolMaterial.ENDER, 3, -2.4f, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.ender_paxel = (Item)new ItemPaxel("ender_paxel", (IItemTier)PattysToolMaterial.ENDER_PAXEL, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.ender_battle_axe = (Item)new ItemBattleaxe("ender_battle_axe", (IItemTier)PattysToolMaterial.ENDER, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.ender_bow = (Item)new ItemCustomBow("ender_bow", new Item.Properties().group(ModTabs.tabPattysCombat).defaultMaxDamage(PattysToolMaterial.ENDER.getMaxUses()));
        ModItems.ender_scythe = new ItemCustomScythe("ender_scythe", (IItemTier)PattysToolMaterial.ENDER, 0.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.ender_hammer = (Item)new ItemCustomHammer("ender_hammer", (IItemTier)PattysToolMaterial.ENDER, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.ender_lumber_axe = (Item)new ItemLumberAxe("ender_lumber_axe", (IItemTier)PattysToolMaterial.ENDER, 5.0f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.ender_excavator = (Item)new ItemExcavator("ender_excavator", (IItemTier)PattysToolMaterial.ENDER, 1, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.ender_helmet = (Item)new ItemMoreArmor("ender_helmet", (IArmorMaterial)PattysArmorMaterial.ENDER, "ender", EquipmentSlotType.HEAD, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.ender_chestplate = (Item)new ItemMoreArmor("ender_chestplate", (IArmorMaterial)PattysArmorMaterial.ENDER, "ender", EquipmentSlotType.CHEST, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.ender_leggings = (Item)new ItemMoreArmor("ender_leggings", (IArmorMaterial)PattysArmorMaterial.ENDER, "ender", EquipmentSlotType.LEGS, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.ender_boots = (Item)new ItemMoreArmor("ender_boots", (IArmorMaterial)PattysArmorMaterial.ENDER, "ender", EquipmentSlotType.FEET, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.coal_pickaxe = (Item)new ItemCustomPickaxe("coal_pickaxe", (IItemTier)PattysToolMaterial.COAL, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.coal_axe = (Item)new ItemCustomAxe("coal_axe", (IItemTier)PattysToolMaterial.COAL, 5.0f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.coal_shovel = (Item)new ItemCustomSpade("coal_shovel", (IItemTier)PattysToolMaterial.COAL, 1.5f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.coal_hoe = (Item)new ItemCustomHoe("coal_hoe", (IItemTier)PattysToolMaterial.COAL, 0.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.coal_sword = (Item)new ItemCustomSword("coal_sword", (IItemTier)PattysToolMaterial.COAL, 3, -2.4f, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.coal_paxel = (Item)new ItemPaxel("coal_paxel", (IItemTier)PattysToolMaterial.COAL_PAXEL, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.coal_battle_axe = (Item)new ItemBattleaxe("coal_battle_axe", (IItemTier)PattysToolMaterial.COAL, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.coal_bow = (Item)new ItemCustomBow("coal_bow", new Item.Properties().group(ModTabs.tabPattysCombat).defaultMaxDamage(PattysToolMaterial.COAL.getMaxUses()));
        ModItems.coal_scythe = new ItemCustomScythe("coal_scythe",(IItemTier)PattysToolMaterial.COAL, 0.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.coal_hammer = (Item)new ItemCustomHammer("coal_hammer", (IItemTier)PattysToolMaterial.COAL, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.coal_lumber_axe = (Item)new ItemLumberAxe("coal_lumber_axe", (IItemTier)PattysToolMaterial.COAL, 5.0f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.coal_excavator = (Item)new ItemExcavator("coal_excavator", (IItemTier)PattysToolMaterial.COAL, 1, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.coal_helmet = (Item)new ItemMoreArmor("coal_helmet", (IArmorMaterial)PattysArmorMaterial.COAL, "coal", EquipmentSlotType.HEAD, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.coal_chestplate = (Item)new ItemMoreArmor("coal_chestplate", (IArmorMaterial)PattysArmorMaterial.COAL, "coal", EquipmentSlotType.CHEST, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.coal_leggings = (Item)new ItemMoreArmor("coal_leggings", (IArmorMaterial)PattysArmorMaterial.COAL, "coal", EquipmentSlotType.LEGS, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.coal_boots = (Item)new ItemMoreArmor("coal_boots", (IArmorMaterial)PattysArmorMaterial.COAL, "coal", EquipmentSlotType.FEET, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.quartz_pickaxe = (Item)new ItemCustomPickaxe("quartz_pickaxe", (IItemTier)PattysToolMaterial.QUARTZ, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.quartz_axe = (Item)new ItemCustomAxe("quartz_axe", (IItemTier)PattysToolMaterial.QUARTZ, 5.0f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.quartz_shovel = (Item)new ItemCustomSpade("quartz_shovel", (IItemTier)PattysToolMaterial.QUARTZ, 1.5f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.quartz_sword = (Item)new ItemCustomSword("quartz_sword", (IItemTier)PattysToolMaterial.QUARTZ, 3, -2.4f, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.quartz_hoe = (Item)new ItemCustomHoe("quartz_hoe", (IItemTier)PattysToolMaterial.QUARTZ, 0.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.quartz_paxel = (Item)new ItemPaxel("quartz_paxel", (IItemTier)PattysToolMaterial.QUARTZ_PAXEL, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.quartz_battle_axe = (Item)new ItemBattleaxe("quartz_battle_axe", (IItemTier)PattysToolMaterial.QUARTZ, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.quartz_bow = (Item)new ItemCustomBow("quartz_bow", new Item.Properties().group(ModTabs.tabPattysCombat).defaultMaxDamage(PattysToolMaterial.QUARTZ.getMaxUses()));
        ModItems.quartz_scythe = new ItemCustomScythe("quartz_scythe",(IItemTier)PattysToolMaterial.QUARTZ, 0.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.quartz_hammer = (Item)new ItemCustomHammer("quartz_hammer", (IItemTier)PattysToolMaterial.QUARTZ, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.quartz_lumber_axe = (Item)new ItemLumberAxe("quartz_lumber_axe", (IItemTier)PattysToolMaterial.QUARTZ, 5.0f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.quartz_excavator = (Item)new ItemExcavator("quartz_excavator", (IItemTier)PattysToolMaterial.QUARTZ, 1, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.quartz_helmet = (Item)new ItemMoreArmor("quartz_helmet", (IArmorMaterial)PattysArmorMaterial.QUARTZ, "quartz", EquipmentSlotType.HEAD, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.quartz_chestplate = (Item)new ItemMoreArmor("quartz_chestplate", (IArmorMaterial)PattysArmorMaterial.QUARTZ, "quartz", EquipmentSlotType.CHEST, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.quartz_leggings = (Item)new ItemMoreArmor("quartz_leggings", (IArmorMaterial)PattysArmorMaterial.QUARTZ, "quartz", EquipmentSlotType.LEGS, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.quartz_boots = (Item)new ItemMoreArmor("quartz_boots", (IArmorMaterial)PattysArmorMaterial.QUARTZ, "quartz", EquipmentSlotType.FEET, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.glowstone_pickaxe = (Item)new ItemCustomPickaxe("glowstone_pickaxe", (IItemTier)PattysToolMaterial.GLOWSTONE, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.glowstone_axe = (Item)new ItemCustomAxe("glowstone_axe", (IItemTier)PattysToolMaterial.GLOWSTONE, 5.0f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.glowstone_shovel = (Item)new ItemCustomSpade("glowstone_shovel", (IItemTier)PattysToolMaterial.GLOWSTONE, 1.5f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.glowstone_sword = (Item)new ItemCustomSword("glowstone_sword", (IItemTier)PattysToolMaterial.GLOWSTONE, 3, -2.4f, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.glowstone_hoe = (Item)new ItemCustomHoe("glowstone_hoe", (IItemTier)PattysToolMaterial.GLOWSTONE, 0.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.glowstone_paxel = (Item)new ItemPaxel("glowstone_paxel", (IItemTier)PattysToolMaterial.GLOWSTONE_PAXEL, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.glowstone_battle_axe = (Item)new ItemBattleaxe("glowstone_battle_axe", (IItemTier)PattysToolMaterial.GLOWSTONE, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.glowstone_bow = (Item)new ItemCustomBow("glowstone_bow", new Item.Properties().group(ModTabs.tabPattysCombat).defaultMaxDamage(PattysToolMaterial.GLOWSTONE.getMaxUses()));
        ModItems.glowstone_scythe = new ItemCustomScythe("glowstone_scythe",(IItemTier)PattysToolMaterial.GLOWSTONE, 0.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.glowstone_hammer = (Item)new ItemCustomHammer("glowstone_hammer", (IItemTier)PattysToolMaterial.GLOWSTONE, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.glowstone_lumber_axe = (Item)new ItemLumberAxe("glowstone_lumber_axe", (IItemTier)PattysToolMaterial.GLOWSTONE, 5.0f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.glowstone_excavator = (Item)new ItemExcavator("glowstone_excavator", (IItemTier)PattysToolMaterial.GLOWSTONE, 1, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.glowstone_helmet = (Item)new ItemMoreArmor("glowstone_helmet", (IArmorMaterial)PattysArmorMaterial.GLOWSTONE, "glowstone", EquipmentSlotType.HEAD, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.glowstone_chestplate = (Item)new ItemMoreArmor("glowstone_chestplate", (IArmorMaterial)PattysArmorMaterial.GLOWSTONE, "glowstone", EquipmentSlotType.CHEST, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.glowstone_leggings = (Item)new ItemMoreArmor("glowstone_leggings", (IArmorMaterial)PattysArmorMaterial.GLOWSTONE, "glowstone", EquipmentSlotType.LEGS, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.glowstone_boots = (Item)new ItemMoreArmor("glowstone_boots", (IArmorMaterial)PattysArmorMaterial.GLOWSTONE, "glowstone", EquipmentSlotType.FEET, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.brick_pickaxe = (Item)new ItemCustomPickaxe("brick_pickaxe", (IItemTier)PattysToolMaterial.BRICK, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.brick_axe = (Item)new ItemCustomAxe("brick_axe", (IItemTier)PattysToolMaterial.BRICK, 5.0f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.brick_shovel = (Item)new ItemCustomSpade("brick_shovel", (IItemTier)PattysToolMaterial.BRICK, 1.5f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.brick_hoe = (Item)new ItemCustomHoe("brick_hoe", (IItemTier)PattysToolMaterial.BRICK, 0.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.brick_sword = (Item)new ItemCustomSword("brick_sword", (IItemTier)PattysToolMaterial.BRICK, 3, -2.4f, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.brick_paxel = (Item)new ItemPaxel("brick_paxel", (IItemTier)PattysToolMaterial.BRICK_PAXEL, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.brick_battle_axe = (Item)new ItemBattleaxe("brick_battle_axe", (IItemTier)PattysToolMaterial.BRICK, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.brick_bow = (Item)new ItemCustomBow("brick_bow", new Item.Properties().group(ModTabs.tabPattysCombat).defaultMaxDamage(PattysToolMaterial.BRICK.getMaxUses()));
        ModItems.brick_scythe = new ItemCustomScythe("brick_scythe", (IItemTier)PattysToolMaterial.BRICK, 0.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.brick_hammer = (Item)new ItemCustomHammer("brick_hammer", (IItemTier)PattysToolMaterial.BRICK, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.brick_lumber_axe = (Item)new ItemLumberAxe("brick_lumber_axe", (IItemTier)PattysToolMaterial.BRICK, 5.0f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.brick_excavator = (Item)new ItemExcavator("brick_excavator", (IItemTier)PattysToolMaterial.BRICK, 1, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.brick_helmet = (Item)new ItemMoreArmor("brick_helmet", (IArmorMaterial)PattysArmorMaterial.BRICK, "brick", EquipmentSlotType.HEAD, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.brick_chestplate = (Item)new ItemMoreArmor("brick_chestplate", (IArmorMaterial)PattysArmorMaterial.BRICK, "brick", EquipmentSlotType.CHEST, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.brick_leggings = (Item)new ItemMoreArmor("brick_leggings", (IArmorMaterial)PattysArmorMaterial.BRICK, "brick", EquipmentSlotType.LEGS, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.brick_boots = (Item)new ItemMoreArmor("brick_boots", (IArmorMaterial)PattysArmorMaterial.BRICK, "brick", EquipmentSlotType.FEET, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.nbrick_pickaxe = (Item)new ItemCustomPickaxe("nbrick_pickaxe", (IItemTier)PattysToolMaterial.NBRICK, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.nbrick_axe = (Item)new ItemCustomAxe("nbrick_axe", (IItemTier)PattysToolMaterial.NBRICK, 5.0f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.nbrick_shovel = (Item)new ItemCustomSpade("nbrick_shovel", (IItemTier)PattysToolMaterial.NBRICK, 1.5f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.nbrick_hoe = (Item)new ItemCustomHoe("nbrick_hoe", (IItemTier)PattysToolMaterial.NBRICK, 0.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.nbrick_sword = (Item)new ItemCustomSword("nbrick_sword", (IItemTier)PattysToolMaterial.NBRICK, 3, -2.4f, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.nbrick_paxel = (Item)new ItemPaxel("nbrick_paxel", (IItemTier)PattysToolMaterial.NBRICK_PAXEL, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.netherbrick_battle_axe = (Item)new ItemBattleaxe("netherbrick_battle_axe", (IItemTier)PattysToolMaterial.NBRICK, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.netherbrick_bow = (Item)new ItemCustomBow("netherbrick_bow", new Item.Properties().group(ModTabs.tabPattysCombat).defaultMaxDamage(PattysToolMaterial.NBRICK.getMaxUses()));
        ModItems.nbrick_scythe = new ItemCustomScythe("nbrick_scythe",(IItemTier)PattysToolMaterial.NBRICK, 0.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.nbrick_hammer = (Item)new ItemCustomHammer("nbrick_hammer", (IItemTier)PattysToolMaterial.NBRICK, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.nbrick_lumber_axe = (Item)new ItemLumberAxe("nbrick_lumber_axe", (IItemTier)PattysToolMaterial.NBRICK, 5.0f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.nbrick_excavator = (Item)new ItemExcavator("nbrick_excavator", (IItemTier)PattysToolMaterial.NBRICK, 1, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.nether_brick_helmet = (Item)new ItemMoreArmor("nether_brick_helmet", (IArmorMaterial)PattysArmorMaterial.NETHER_BRICK, "nether_brick", EquipmentSlotType.HEAD, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.nether_brick_chestplate = (Item)new ItemMoreArmor("nether_brick_chestplate", (IArmorMaterial)PattysArmorMaterial.NETHER_BRICK, "nether_brick", EquipmentSlotType.CHEST, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.nether_brick_leggings = (Item)new ItemMoreArmor("nether_brick_leggings", (IArmorMaterial)PattysArmorMaterial.NETHER_BRICK, "nether_brick", EquipmentSlotType.LEGS, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.nether_brick_boots = (Item)new ItemMoreArmor("nether_brick_boots", (IArmorMaterial)PattysArmorMaterial.NETHER_BRICK, "nether_brick", EquipmentSlotType.FEET, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.redstone_pickaxe = (Item)new ItemCustomPickaxe("redstone_pickaxe", (IItemTier)PattysToolMaterial.REDSTONE, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.redstone_axe = (Item)new ItemCustomAxe("redstone_axe", (IItemTier)PattysToolMaterial.REDSTONE, 5.0f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.redstone_shovel = (Item)new ItemCustomSpade("redstone_shovel", (IItemTier)PattysToolMaterial.REDSTONE, 1.5f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.redstone_hoe = (Item)new ItemCustomHoe("redstone_hoe", (IItemTier)PattysToolMaterial.REDSTONE, 0.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.redstone_sword = (Item)new ItemCustomSword("redstone_sword", (IItemTier)PattysToolMaterial.REDSTONE, 3, -2.4f, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.redstone_paxel = (Item)new ItemPaxel("redstone_paxel", (IItemTier)PattysToolMaterial.REDSTONE_PAXEL, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.redstone_battle_axe = (Item)new ItemBattleaxe("redstone_battle_axe", (IItemTier)PattysToolMaterial.REDSTONE, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.redstone_bow = (Item)new ItemCustomBow("redstone_bow", new Item.Properties().group(ModTabs.tabPattysCombat).defaultMaxDamage(PattysToolMaterial.REDSTONE.getMaxUses()));
        ModItems.redstone_scythe = new ItemCustomScythe("redstone_scythe",(IItemTier)PattysToolMaterial.REDSTONE, 0.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.redstone_hammer = (Item)new ItemCustomHammer("redstone_hammer", (IItemTier)PattysToolMaterial.REDSTONE, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.redstone_lumber_axe = (Item)new ItemLumberAxe("redstone_lumber_axe", (IItemTier)PattysToolMaterial.REDSTONE, 5.0f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.redstone_excavator = (Item)new ItemExcavator("redstone_excavator", (IItemTier)PattysToolMaterial.REDSTONE, 1, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.redstone_helmet = (Item)new ItemMoreArmor("redstone_helmet", (IArmorMaterial)PattysArmorMaterial.REDSTONE, "redstone", EquipmentSlotType.HEAD, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.redstone_chestplate = (Item)new ItemMoreArmor("redstone_chestplate", (IArmorMaterial)PattysArmorMaterial.REDSTONE, "redstone", EquipmentSlotType.CHEST, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.redstone_leggings = (Item)new ItemMoreArmor("redstone_leggings", (IArmorMaterial)PattysArmorMaterial.REDSTONE, "redstone", EquipmentSlotType.LEGS, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.redstone_boots = (Item)new ItemMoreArmor("redstone_boots", (IArmorMaterial)PattysArmorMaterial.REDSTONE, "redstone", EquipmentSlotType.FEET, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.blaze_pickaxe = (Item)new ItemCustomPickaxe("blaze_pickaxe", (IItemTier)PattysToolMaterial.BLAZE, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.blaze_axe = (Item)new ItemCustomAxe("blaze_axe", (IItemTier)PattysToolMaterial.BLAZE, 5.0f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.blaze_shovel = (Item)new ItemCustomSpade("blaze_shovel", (IItemTier)PattysToolMaterial.BLAZE, 1.5f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.blaze_hoe = (Item)new ItemCustomHoe("blaze_hoe", (IItemTier)PattysToolMaterial.BLAZE, 0.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.blaze_sword = (Item)new ItemCustomSword("blaze_sword", (IItemTier)PattysToolMaterial.BLAZE, 3, -2.4f, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.blaze_paxel = (Item)new ItemPaxel("blaze_paxel", (IItemTier)PattysToolMaterial.BLAZE_PAXEL, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.blaze_battle_axe = (Item)new ItemBattleaxe("blaze_battle_axe", (IItemTier)PattysToolMaterial.BLAZE, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.blaze_bow = (Item)new ItemCustomBow("blaze_bow", new Item.Properties().group(ModTabs.tabPattysCombat).defaultMaxDamage(PattysToolMaterial.BLAZE.getMaxUses()));
        ModItems.blaze_scythe = new ItemCustomScythe("blaze_scythe", (IItemTier)PattysToolMaterial.BLAZE, 0.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.blaze_hammer = (Item)new ItemCustomHammer("blaze_hammer", (IItemTier)PattysToolMaterial.BLAZE, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.blaze_lumber_axe = (Item)new ItemLumberAxe("blaze_lumber_axe", (IItemTier)PattysToolMaterial.BLAZE, 5.0f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.blaze_excavator = (Item)new ItemExcavator("blaze_excavator", (IItemTier)PattysToolMaterial.BLAZE, 1, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.blaze_helmet = (Item)new ItemMoreArmor("blaze_helmet", (IArmorMaterial)PattysArmorMaterial.BLAZE, "blaze", EquipmentSlotType.HEAD, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.blaze_chestplate = (Item)new ItemMoreArmor("blaze_chestplate", (IArmorMaterial)PattysArmorMaterial.BLAZE, "blaze", EquipmentSlotType.CHEST, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.blaze_leggings = (Item)new ItemMoreArmor("blaze_leggings", (IArmorMaterial)PattysArmorMaterial.BLAZE, "blaze", EquipmentSlotType.LEGS, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.blaze_boots = (Item)new ItemMoreArmor("blaze_boots", (IArmorMaterial)PattysArmorMaterial.BLAZE, "blaze", EquipmentSlotType.FEET, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.magma_cream_pickaxe = (Item)new ItemCustomPickaxe("magma_cream_pickaxe", (IItemTier)PattysToolMaterial.MAGMACREAM, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.magma_cream_axe = (Item)new ItemCustomAxe("magma_cream_axe", (IItemTier)PattysToolMaterial.MAGMACREAM, 5.0f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.magma_cream_shovel = (Item)new ItemCustomSpade("magma_cream_shovel", (IItemTier)PattysToolMaterial.MAGMACREAM, 1.5f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.magma_cream_hoe = (Item)new ItemCustomHoe("magma_cream_hoe", (IItemTier)PattysToolMaterial.MAGMACREAM, 0.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.magma_cream_sword = (Item)new ItemCustomSword("magma_cream_sword", (IItemTier)PattysToolMaterial.MAGMACREAM, 3, -2.4f, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.magma_cream_paxel = (Item)new ItemPaxel("magma_cream_paxel", (IItemTier)PattysToolMaterial.MAGMACREAM_PAXEL, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.magmacream_battle_axe = (Item)new ItemBattleaxe("magmacream_battle_axe", (IItemTier)PattysToolMaterial.MAGMACREAM, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.magma_cream_bow = (Item)new ItemCustomBow("magma_cream_bow", new Item.Properties().group(ModTabs.tabPattysCombat).defaultMaxDamage(PattysToolMaterial.MAGMACREAM.getMaxUses()));
        ModItems.magma_cream_scythe = new ItemCustomScythe("magma_cream_scythe", (IItemTier)PattysToolMaterial.MAGMACREAM, 0.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.magma_cream_hammer = (Item)new ItemCustomHammer("magma_cream_hammer", (IItemTier)PattysToolMaterial.MAGMACREAM, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.magma_cream_lumber_axe = (Item)new ItemLumberAxe("magma_cream_lumber_axe", (IItemTier)PattysToolMaterial.MAGMACREAM, 5.0f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.magma_cream_excavator = (Item)new ItemExcavator("magma_cream_excavator", (IItemTier)PattysToolMaterial.MAGMACREAM, 1, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.magma_cream_helmet = (Item)new ItemMoreArmor("magma_cream_helmet", (IArmorMaterial)PattysArmorMaterial.MAGMA_CREAM, "magma_cream", EquipmentSlotType.HEAD, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.magma_cream_chestplate = (Item)new ItemMoreArmor("magma_cream_chestplate", (IArmorMaterial)PattysArmorMaterial.MAGMA_CREAM, "magma_cream", EquipmentSlotType.CHEST, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.magma_cream_leggings = (Item)new ItemMoreArmor("magma_cream_leggings", (IArmorMaterial)PattysArmorMaterial.MAGMA_CREAM, "magma_cream", EquipmentSlotType.LEGS, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.magma_cream_boots = (Item)new ItemMoreArmor("magma_cream_boots", (IArmorMaterial)PattysArmorMaterial.MAGMA_CREAM, "magma_cream", EquipmentSlotType.FEET, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.sandstone_pickaxe = (Item)new ItemCustomPickaxe("sandstone_pickaxe", (IItemTier)PattysToolMaterial.SANDSTONE, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.sandstone_axe = (Item)new ItemCustomAxe("sandstone_axe", (IItemTier)PattysToolMaterial.SANDSTONE, 5.0f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.sandstone_shovel = (Item)new ItemCustomSpade("sandstone_shovel", (IItemTier)PattysToolMaterial.SANDSTONE, 1.5f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.sandstone_hoe = (Item)new ItemCustomHoe("sandstone_hoe", (IItemTier)PattysToolMaterial.SANDSTONE, 0.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.sandstone_sword = (Item)new ItemCustomSword("sandstone_sword", (IItemTier)PattysToolMaterial.SANDSTONE, 3, -2.4f, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.sandstone_paxel = (Item)new ItemPaxel("sandstone_paxel", (IItemTier)PattysToolMaterial.SANDSTONE_PAXEL, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.sandstone_battle_axe = (Item)new ItemBattleaxe("sandstone_battle_axe", (IItemTier)PattysToolMaterial.SANDSTONE, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.sandstone_bow = (Item)new ItemCustomBow("sandstone_bow", new Item.Properties().group(ModTabs.tabPattysCombat).defaultMaxDamage(PattysToolMaterial.SANDSTONE.getMaxUses()));
        ModItems.sandstone_scythe = new ItemCustomScythe("sandstone_scythe", (IItemTier)PattysToolMaterial.SANDSTONE, 0.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.sandstone_hammer = (Item)new ItemCustomHammer("sandstone_hammer", (IItemTier)PattysToolMaterial.SANDSTONE, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.sandstone_lumber_axe = (Item)new ItemLumberAxe("sandstone_lumber_axe", (IItemTier)PattysToolMaterial.SANDSTONE, 5.0f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.sandstone_helmet = (Item)new ItemMoreArmor("sandstone_helmet", (IArmorMaterial)PattysArmorMaterial.SANDSTONE, "sandstone", EquipmentSlotType.HEAD, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.sandstone_chestplate = (Item)new ItemMoreArmor("sandstone_chestplate", (IArmorMaterial)PattysArmorMaterial.SANDSTONE, "sandstone", EquipmentSlotType.CHEST, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.sandstone_leggings = (Item)new ItemMoreArmor("sandstone_leggings", (IArmorMaterial)PattysArmorMaterial.SANDSTONE, "sandstone", EquipmentSlotType.LEGS, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.sandstone_boots = (Item)new ItemMoreArmor("sandstone_boots", (IArmorMaterial)PattysArmorMaterial.SANDSTONE, "sandstone", EquipmentSlotType.FEET, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.soul_sand_pickaxe = (Item)new ItemCustomPickaxe("soul_sand_pickaxe", (IItemTier)PattysToolMaterial.SOULSAND, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.soul_sand_axe = (Item)new ItemCustomAxe("soul_sand_axe", (IItemTier)PattysToolMaterial.SOULSAND, 5.0f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.soul_sand_shovel = (Item)new ItemCustomSpade("soul_sand_shovel", (IItemTier)PattysToolMaterial.SOULSAND, 1.5f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.soul_sand_hoe = (Item)new ItemCustomHoe("soul_sand_hoe", (IItemTier)PattysToolMaterial.SOULSAND, 0.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.soul_sand_sword = (Item)new ItemCustomSword("soul_sand_sword", (IItemTier)PattysToolMaterial.SOULSAND, 3, -2.4f, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.soul_sand_paxel = (Item)new ItemPaxel("soul_sand_paxel", (IItemTier)PattysToolMaterial.SOULSAND_PAXEL, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.soulsand_battle_axe = (Item)new ItemBattleaxe("soulsand_battle_axe", (IItemTier)PattysToolMaterial.SOULSAND, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.soul_sand_bow = (Item)new ItemCustomBow("soul_sand_bow", new Item.Properties().group(ModTabs.tabPattysCombat).defaultMaxDamage(PattysToolMaterial.SOULSAND.getMaxUses()));
        ModItems.soul_sand_scythe = new ItemCustomScythe("soul_sand_scythe", (IItemTier)PattysToolMaterial.SOULSAND, 0.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.soul_sand_hammer = (Item)new ItemCustomHammer("soul_sand_hammer", (IItemTier)PattysToolMaterial.SOULSAND, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.soul_sand_lumber_axe = (Item)new ItemLumberAxe("soul_sand_lumber_axe", (IItemTier)PattysToolMaterial.SOULSAND, 5.0f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.soul_sand_helmet = (Item)new ItemMoreArmor("soul_sand_helmet", (IArmorMaterial)PattysArmorMaterial.SOUL_SAND, "soul_sand", EquipmentSlotType.HEAD, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.soul_sand_chestplate = (Item)new ItemMoreArmor("soul_sand_chestplate", (IArmorMaterial)PattysArmorMaterial.SOUL_SAND, "soul_sand", EquipmentSlotType.CHEST, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.soul_sand_leggings = (Item)new ItemMoreArmor("soul_sand_leggings", (IArmorMaterial)PattysArmorMaterial.SOUL_SAND, "soul_sand", EquipmentSlotType.LEGS, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.soul_sand_boots = (Item)new ItemMoreArmor("soul_sand_boots", (IArmorMaterial)PattysArmorMaterial.SOUL_SAND, "soul_sand", EquipmentSlotType.FEET, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.netherbrickred_pickaxe = (Item)new ItemCustomPickaxe("netherbrickred_pickaxe", (IItemTier)PattysToolMaterial.NETHERBRICKRED, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.netherbrickred_axe = (Item)new ItemCustomAxe("netherbrickred_axe", (IItemTier)PattysToolMaterial.NETHERBRICKRED, 5.0f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.netherbrickred_shovel = (Item)new ItemCustomSpade("netherbrickred_shovel", (IItemTier)PattysToolMaterial.NETHERBRICKRED, 1.5f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.netherbrickred_hoe = (Item)new ItemCustomHoe("netherbrickred_hoe", (IItemTier)PattysToolMaterial.NETHERBRICKRED, 0.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.netherbrickred_sword = (Item)new ItemCustomSword("netherbrickred_sword", (IItemTier)PattysToolMaterial.NETHERBRICKRED, 3, -2.4f, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.netherbrickred_paxel = (Item)new ItemPaxel("netherbrickred_paxel", (IItemTier)PattysToolMaterial.NETHERBRICKRED_PAXEL, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.netherbrickred_battle_axe = (Item)new ItemBattleaxe("netherbrickred_battle_axe", (IItemTier)PattysToolMaterial.NETHERBRICKRED, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.netherbrickred_bow = (Item)new ItemCustomBow("netherbrickred_bow", new Item.Properties().group(ModTabs.tabPattysCombat).defaultMaxDamage(PattysToolMaterial.NETHERBRICKRED.getMaxUses()));
        ModItems.netherbrickred_scythe = new ItemCustomScythe("netherbrickred_scythe", (IItemTier)PattysToolMaterial.NETHERBRICKRED, 0.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.netherbrickred_hammer = (Item)new ItemCustomHammer("netherbrickred_hammer", (IItemTier)PattysToolMaterial.NETHERBRICKRED, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.netherbrickred_lumber_axe = (Item)new ItemLumberAxe("netherbrickred_lumber_axe", (IItemTier)PattysToolMaterial.NETHERBRICKRED, 5.0f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.red_netherbrick_helmet = (Item)new ItemMoreArmor("red_netherbrick_helmet", (IArmorMaterial)PattysArmorMaterial.RED_NETHER_BRICK, "red_nether_brick", EquipmentSlotType.HEAD, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.red_netherbrick_chestplate = (Item)new ItemMoreArmor("red_netherbrick_chestplate", (IArmorMaterial)PattysArmorMaterial.RED_NETHER_BRICK, "red_nether_brick", EquipmentSlotType.CHEST, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.red_netherbrick_leggings = (Item)new ItemMoreArmor("red_netherbrick_leggings", (IArmorMaterial)PattysArmorMaterial.RED_NETHER_BRICK, "red_nether_brick", EquipmentSlotType.LEGS, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.red_netherbrick_boots = (Item)new ItemMoreArmor("red_netherbrick_boots", (IArmorMaterial)PattysArmorMaterial.RED_NETHER_BRICK, "red_nether_brick", EquipmentSlotType.FEET, new Item.Properties().group(ModTabs.tabPattysCombat));
        ModItems.wooden_paxel = (Item)new ItemPaxel("wooden_paxel", (IItemTier)PattysToolMaterial.WOOD_PAXEL, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.wooden_battle_axe = (Item)new ItemBattleaxe("wooden_battle_axe", (IItemTier)ItemTier.WOOD, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.wood_scythe = (Item)new ItemCustomScythe("wood_scythe", (IItemTier)ItemTier.WOOD, 0.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.wooden_hammer = (Item)new ItemCustomHammer("wooden_hammer", (IItemTier)ItemTier.WOOD, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.wooden_lumber_axe = (Item)new ItemLumberAxe("wooden_lumber_axe", (IItemTier)ItemTier.WOOD, 5.0f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.stone_paxel = (Item)new ItemPaxel("stone_paxel", (IItemTier)PattysToolMaterial.STONE_PAXEL, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.stone_battle_axe = (Item)new ItemBattleaxe("stone_battle_axe", (IItemTier)ItemTier.STONE, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.stone_bow = (Item)new ItemCustomBow("stone_bow", new Item.Properties().group(ModTabs.tabPattysCombat).defaultMaxDamage(ItemTier.STONE.getMaxUses()));
        ModItems.stone_scythe = new ItemCustomScythe("stone_scythe", (IItemTier)ItemTier.STONE, 0.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.stone_hammer = (Item)new ItemCustomHammer("stone_hammer", (IItemTier)ItemTier.STONE, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.stone_lumber_axe = (Item)new ItemLumberAxe("stone_lumber_axe", (IItemTier)ItemTier.STONE, 5.0f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.iron_paxel = (Item)new ItemPaxel("iron_paxel", (IItemTier)PattysToolMaterial.IRON_PAXEL, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.iron_battle_axe = (Item)new ItemBattleaxe("iron_battle_axe", (IItemTier)ItemTier.IRON, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.iron_bow = (Item)new ItemCustomBow("iron_bow", new Item.Properties().group(ModTabs.tabPattysCombat).defaultMaxDamage(ItemTier.IRON.getMaxUses()));
        ModItems.iron_scythe = new ItemCustomScythe("iron_scythe", (IItemTier)ItemTier.IRON, 0.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.iron_hammer = (Item)new ItemCustomHammer("iron_hammer", (IItemTier)ItemTier.IRON, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.iron_lumber_axe = (Item)new ItemLumberAxe("iron_lumber_axe", (IItemTier)ItemTier.IRON, 5.0f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.iron_excavator = (Item)new ItemExcavator("iron_excavator", (IItemTier)ItemTier.IRON, 1, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.gold_paxel = (Item)new ItemPaxel("gold_paxel", (IItemTier)PattysToolMaterial.GOLD_PAXEL, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.gold_battle_axe = (Item)new ItemBattleaxe("gold_battle_axe", (IItemTier)ItemTier.GOLD, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.gold_bow = (Item)new ItemCustomBow("gold_bow", new Item.Properties().group(ModTabs.tabPattysCombat).defaultMaxDamage(ItemTier.GOLD.getMaxUses()));
        ModItems.gold_scythe = new ItemCustomScythe("gold_scythe", (IItemTier)ItemTier.GOLD, 0.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.gold_hammer = (Item)new ItemCustomHammer("gold_hammer", (IItemTier)ItemTier.GOLD, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.gold_lumber_axe = (Item)new ItemLumberAxe("gold_lumber_axe", (IItemTier)ItemTier.GOLD, 5.0f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.gold_excavator = (Item)new ItemExcavator("gold_excavator", (IItemTier)ItemTier.GOLD, 1, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.diamond_paxel = (Item)new ItemPaxel("diamond_paxel", (IItemTier)PattysToolMaterial.DIAMOND_PAXEL, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.diamond_battle_axe = (Item)new ItemBattleaxe("diamond_battle_axe", (IItemTier)ItemTier.DIAMOND, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.diamond_bow = (Item)new ItemCustomBow("diamond_bow", new Item.Properties().group(ModTabs.tabPattysCombat).defaultMaxDamage(ItemTier.DIAMOND.getMaxUses()));
        ModItems.diamond_scythe = new ItemCustomScythe("diamond_scythe", (IItemTier)ItemTier.DIAMOND, 0.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.diamond_hammer = (Item)new ItemCustomHammer("diamond_hammer", (IItemTier)ItemTier.DIAMOND, 1, -2.8f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.diamond_lumber_axe = (Item)new ItemLumberAxe("diamond_lumber_axe", (IItemTier)ItemTier.DIAMOND, 5.0f, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.diamond_excavator = (Item)new ItemExcavator("diamond_excavator", (IItemTier)ItemTier.DIAMOND, 1, -3.0f, new Item.Properties().group(ModTabs.tabPattysTools));
        ModItems.fried_egg = new ItemCustomFood("fried_egg", new Item.Properties().group(ModTabs.tabPattysFood).food(PattysFoods.FRIED_EGG));
        ModItems.bacon_raw = new ItemCustomFood("bacon_raw", new Item.Properties().group(ModTabs.tabPattysFood).food(PattysFoods.BACON_RAW));
        ModItems.bacon_cooked = new ItemCustomFood("bacon_cooked", new Item.Properties().group(ModTabs.tabPattysFood).food(PattysFoods.BACON_COOKED));
        ModItems.sausage_raw = new ItemCustomFood("sausage_raw", new Item.Properties().group(ModTabs.tabPattysFood).food(PattysFoods.SAUSAGE_RAW));
        ModItems.sausage_cooked = new ItemCustomFood("sausage_cooked", new Item.Properties().group(ModTabs.tabPattysFood).food(PattysFoods.SAUSAGE_COOKED));
        ModItems.baguette_roll = new ItemCustomFood("baguette_roll", new Item.Properties().group(ModTabs.tabPattysFood).food(PattysFoods.BAGUETTE_ROLL));
        ModItems.baguette_bacon = new ItemCustomFood("baguette_bacon", new Item.Properties().group(ModTabs.tabPattysFood).food(PattysFoods.BAGUETTE_BACON));
        ModItems.baguette_egg = new ItemCustomFood("baguette_egg", new Item.Properties().group(ModTabs.tabPattysFood).food(PattysFoods.BAGUETTE_EGG));
        ModItems.baguette_eggbacon = new ItemCustomFood("baguette_eggbacon", new Item.Properties().group(ModTabs.tabPattysFood).food(PattysFoods.BAGUETTE_EGGBACON));
        ModItems.baguette_sausage = new ItemCustomFood("baguette_sausage", new Item.Properties().group(ModTabs.tabPattysFood).food(PattysFoods.BAGUETTE_SAUSAGE));
        ModItems.baguette_baconsausage = new ItemCustomFood("baguette_baconsausage", new Item.Properties().group(ModTabs.tabPattysFood).food(PattysFoods.BAGUETTE_BACONSAUSAGE));
        ModItems.baguette_eggsausage = new ItemCustomFood("baguette_eggsausage", new Item.Properties().group(ModTabs.tabPattysFood).food(PattysFoods.BAGUETTE_EGGSAUSAGE));
        ModItems.baguette_eggbaconsausage = new ItemCustomFood("baguette_eggbaconsausage", new Item.Properties().group(ModTabs.tabPattysFood).food(PattysFoods.BAGUETTE_EGGBACONSAUSAGE));
        ModItems.apple_pie = new ItemCustomFood("apple_pie", new Item.Properties().group(ModTabs.tabPattysFood).food(PattysFoods.APPLE_PIE));
        ModItems.toast = new ItemCustomFood("toast", new Item.Properties().group(ModTabs.tabPattysFood).food(PattysFoods.TOAST));
        ModItems.flour = new ItemBase("flour", new Item.Properties().group(ModTabs.tabPattysFood));
        ModItems.fruit_salad = new ItemCustomFood("fruit_salad", new Item.Properties().group(ModTabs.tabPattysFood).food(PattysFoods.FRUIT_SALAD));
        ModItems.double_choc_cookie = new ItemCustomFood("double_choc_cookie", new Item.Properties().group(ModTabs.tabPattysFood).food(PattysFoods.DOUBLE_CHOC_COOKIE));
        ModItems.apple_juice = new ItemDrinkable("apple_juice", new Item.Properties().group(ModTabs.tabPattysFood).food(PattysFoods.APPLE_JUICE));
        ModItems.melon_juice = new ItemDrinkable("melon_juice", new Item.Properties().group(ModTabs.tabPattysFood).food(PattysFoods.MELON_JUICE));
        ModItems.carrot_juice = new ItemDrinkable("carrot_juice", new Item.Properties().group(ModTabs.tabPattysFood).food(PattysFoods.CARROT_JUICE));
        ModItems.beetroot_juice = new ItemDrinkable("beetroot_juice", new Item.Properties().group(ModTabs.tabPattysFood).food(PattysFoods.BEETROOT_JUICE));
        ModItems.pumpkin_juice = new ItemDrinkable("pumpkin_juice", new Item.Properties().group(ModTabs.tabPattysFood).food(PattysFoods.PUMPKIN_JUICE));
        ModItems.bottle_milk = new ItemMilkBottle("bottle_milk", new Item.Properties().group(ModTabs.tabPattysFood).food(PattysFoods.MILK_BOTTLE));
        ModItems.bottle_chocolate_milk = new ItemChocolateMilk("bottle_chocolate_milk", new Item.Properties().group(ModTabs.tabPattysFood).food(PattysFoods.CHOCOLATE_MILK_BOTTLE));
        ModItems.apple_slushie = new ItemDrinkable("apple_slushie", new Item.Properties().group(ModTabs.tabPattysFood).food(PattysFoods.APPLE_SLUSHIE));
        ModItems.melon_slushie = new ItemDrinkable("melon_slushie", new Item.Properties().group(ModTabs.tabPattysFood).food(PattysFoods.MELON_SLUSHIE));
        ModItems.carrot_slushie = new ItemDrinkable("carrot_slushie", new Item.Properties().group(ModTabs.tabPattysFood).food(PattysFoods.CARROT_SLUSHIE));
        ModItems.beetroot_slushie = new ItemDrinkable("beetroot_slushie", new Item.Properties().group(ModTabs.tabPattysFood).food(PattysFoods.BEETROOT_SLUSHIE));
        ModItems.pumpkin_slushie = new ItemDrinkable("pumpkin_slushie", new Item.Properties().group(ModTabs.tabPattysFood).food(PattysFoods.PUMPKIN_SLUSHIE));
        ModItems.apple_smoothie = new ItemDrinkable("apple_smoothie", new Item.Properties().group(ModTabs.tabPattysFood).food(PattysFoods.APPLE_SMOOTHIE));
        ModItems.melon_smoothie = new ItemDrinkable("melon_smoothie", new Item.Properties().group(ModTabs.tabPattysFood).food(PattysFoods.MELON_SMOOTHIE));
        ModItems.carrot_smoothie = new ItemDrinkable("carrot_smoothie", new Item.Properties().group(ModTabs.tabPattysFood).food(PattysFoods.CARROT_SMOOTHIE));
        ModItems.beetroot_smoothie = new ItemDrinkable("beetroot_smoothie", new Item.Properties().group(ModTabs.tabPattysFood).food(PattysFoods.BEETROOT_SMOOTHIE));
        ModItems.pumpkin_smoothie = new ItemDrinkable("pumpkin_smoothie", new Item.Properties().group(ModTabs.tabPattysFood).food(PattysFoods.PUMPKIN_SMOOTHIE));
        final String name = "miners_helmet";
        final PattysArmorMaterial miner = PattysArmorMaterial.MINER;
        final String armorType = "miner";
        final EquipmentSlotType head = EquipmentSlotType.HEAD;
        ModItems.miners_helmet = (Item)new ItemMoreArmor(name, (IArmorMaterial)miner, armorType, EquipmentSlotType.HEAD, new Item.Properties().group(ModTabs.tabPattysMisc));
        ModItems.magnet = new ItemMagnet("magnet", new Item.Properties().group(ModTabs.tabPattysMisc));
        ModItems.ring_of_flight = new ItemFlightRing("ring_of_flight", new Item.Properties().group(ModTabs.tabPattysMisc));
        ModItems.sweet_berrie_pie = new ItemCustomFood("sweet_berrie_pie", new Item.Properties().group(ModTabs.tabPattysFood).food(PattysFoods.SWEET_BERRIE_PIE));
    }
}
